// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI0FtFVvLglOBaaUA2mvrvO4f0hVhp9vY',
    appId: '1:719937867729:web:10372873ffa26f73de5af0',
    messagingSenderId: '719937867729',
    projectId: 'boxwood-sandbox-440309-c3',
    authDomain: 'boxwood-sandbox-440309-c3.firebaseapp.com',
    storageBucket: 'boxwood-sandbox-440309-c3.firebasestorage.app',
    measurementId: 'G-EMJ9CH2FSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12L9vttqgbyEu8ulRkSHSBuwLwui7uCQ',
    appId: '1:719937867729:android:97515f518e51b1dbde5af0',
    messagingSenderId: '719937867729',
    projectId: 'boxwood-sandbox-440309-c3',
    storageBucket: 'boxwood-sandbox-440309-c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxgv7KilYh3lkiWbrtoWYWWT1po0E9NvA',
    appId: '1:719937867729:ios:dd13c81fb5cc6c52de5af0',
    messagingSenderId: '719937867729',
    projectId: 'boxwood-sandbox-440309-c3',
    storageBucket: 'boxwood-sandbox-440309-c3.firebasestorage.app',
    androidClientId: '719937867729-plihpcoh7l3dn90ro89tgv5ap4mucvv0.apps.googleusercontent.com',
    iosClientId: '719937867729-pnlppp87a256llf0mpt2lmsm1t0kqh85.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisher2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxgv7KilYh3lkiWbrtoWYWWT1po0E9NvA',
    appId: '1:719937867729:ios:dd13c81fb5cc6c52de5af0',
    messagingSenderId: '719937867729',
    projectId: 'boxwood-sandbox-440309-c3',
    storageBucket: 'boxwood-sandbox-440309-c3.firebasestorage.app',
    androidClientId: '719937867729-plihpcoh7l3dn90ro89tgv5ap4mucvv0.apps.googleusercontent.com',
    iosClientId: '719937867729-pnlppp87a256llf0mpt2lmsm1t0kqh85.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisher2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI0FtFVvLglOBaaUA2mvrvO4f0hVhp9vY',
    appId: '1:719937867729:web:e19be7c11a09c651de5af0',
    messagingSenderId: '719937867729',
    projectId: 'boxwood-sandbox-440309-c3',
    authDomain: 'boxwood-sandbox-440309-c3.firebaseapp.com',
    storageBucket: 'boxwood-sandbox-440309-c3.firebasestorage.app',
    measurementId: 'G-DSTLVPZ4M4',
  );
}
